---
- hosts: blog
  become: yes

  vars:
    - new_mysql_root_password: "<password goes here>"
    - application_user_name: "<username goes here>"
    - database_for_application: "<DB name goes here>"
    - application_user_password: "<App user password goes here>"
    - remote_host_ip: "%" # Change for Other IP's
    - domain_name: "test.domain.com" # Put the domain name here
    - php_version: "php7.3"  # To install php7.4 just replace the 3 with 4

  roles:
    - patching
    - install_mysql
    - install_nginx
    - install_php
    - finalization