---
- name: Copy Repo For Nginx
  template:
    src: ../templates/nginx.repo.j2
    dest: /etc/yum.repos.d/nginx.repo

- name: Install Nginx Webserver
  yum: name=nginx update_cache=yes state=latest

- name: Start and Enable Nginx webserver
  service: name=nginx state=started enabled=yes

- name: Copy Nginx configuration
  template:
    src: ../templates/server.conf.j2
    dest: /etc/nginx/conf.d/server.conf
